
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LL_ABRE = 3;
  public static final int CADENA = 22;
  public static final int OR = 11;
  public static final int D_PUNTOS = 5;
  public static final int L_MINUSCULA = 16;
  public static final int POSITIVA = 13;
  public static final int FLECHA = 8;
  public static final int CONCAT = 12;
  public static final int ID = 20;
  public static final int PORCENTAJE = 10;
  public static final int KLEENE = 14;
  public static final int CARACTER = 21;
  public static final int COMA = 7;
  public static final int L_MAYUSCULA = 17;
  public static final int EOF = 0;
  public static final int DIGITO = 18;
  public static final int LL_CIERRA = 4;
  public static final int CONJ = 2;
  public static final int ESPECIAL = 19;
  public static final int error = 1;
  public static final int OPCIONAL = 15;
  public static final int P_COMA = 6;
  public static final int VIRGULILLA = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJ",
  "LL_ABRE",
  "LL_CIERRA",
  "D_PUNTOS",
  "P_COMA",
  "COMA",
  "FLECHA",
  "VIRGULILLA",
  "PORCENTAJE",
  "OR",
  "CONCAT",
  "POSITIVA",
  "KLEENE",
  "OPCIONAL",
  "L_MINUSCULA",
  "L_MAYUSCULA",
  "DIGITO",
  "ESPECIAL",
  "ID",
  "CARACTER",
  "CADENA"
  };
}

